CREATE TABLE IF NOT EXISTS public.utente
(
    codice integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(20) COLLATE pg_catalog."default",
    cognome character varying(20) COLLATE pg_catalog."default",
    email character varying(40) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    user_name character varying(40) COLLATE pg_catalog."default",
    date_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT utente_pkey PRIMARY KEY (codice),
    CONSTRAINT email UNIQUE (email),
    CONSTRAINT username UNIQUE (user_name)
)

CREATE TABLE IF NOT EXISTS public.ruolo
(
    nome character varying(40) COLLATE pg_catalog."default" NOT NULL,
    descrizione character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT ruolo_pkey PRIMARY KEY (nome)
)

CREATE TABLE IF NOT EXISTS public.utente_ruolo
(
    codice_utente integer NOT NULL,
    nome_ruolo character varying COLLATE pg_catalog."default" NOT NULL,
    created_at date NOT NULL DEFAULT now(),
    CONSTRAINT utente_ruolo_pkey PRIMARY KEY (codice_utente, nome_ruolo),
    CONSTRAINT ruolo FOREIGN KEY (nome_ruolo)
        REFERENCES public.ruolo (nome) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT utente FOREIGN KEY (codice_utente)
        REFERENCES public.utente (codice) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)